# Generated by Django 4.1.2 on 2022-10-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_textbook.department')),
            ],
        ),
        migrations.AlterField(
            model_name='textbook',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_textbook.course'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_textbook.department'),
        ),
    ]
