# Generated by Django 4.1.2 on 2022-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('class_description', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('edition', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Textbook',
        ),
    ]
