# Generated by Django 4.1.2 on 2022-11-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('graduation_year', models.IntegerField()),
                ('major', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='textbook',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='post_textbook.user'),
            preserve_default=False,
        ),
    ]
