# Generated by Django 4.1.2 on 2022-10-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0002_department_course_alter_textbook_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='post_textbook.department'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='post_textbook.course'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='post_textbook.department'),
        ),
    ]
