# Generated by Django 4.1.2 on 2022-10-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0002_auto_20221021_1352'),
        ('post_textbook', '0003_alter_course_department_alter_textbook_course_and_more'),
    ]

    operations = [
    ]
