# Generated by Django 4.1.2 on 2022-10-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0003_course_department_textbook_delete_textbookupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='course',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbook',
            name='cover',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbook',
            name='department',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbook',
            name='publisher',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
