# Generated by Django 4.1.2 on 2022-11-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0003_alter_textbook_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='cover',
            field=models.ImageField(default=None, upload_to=None),
            preserve_default=False,
        ),
    ]
