# Generated by Django 4.1.2 on 2022-10-18 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0005_alter_textbook_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='cover',
        ),
    ]
