# Generated by Django 4.1.2 on 2022-11-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0005_alter_textbook_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='ISBN',
            field=models.IntegerField(),
        ),
    ]
