# Generated by Django 4.1.2 on 2022-12-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_textbook', '0008_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
