# Generated by Django 4.1.2 on 2022-12-07 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_friendrequests_friends_delete_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequests',
            old_name='friend_requests',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='friends',
            old_name='friends',
            new_name='users',
        ),
    ]
