# Generated by Django 4.1.2 on 2022-11-05 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('direct_messages', '0002_alter_message_conversation_alter_message_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_a',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_b_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_b',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_a_messages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
