# Generated by Django 4.1.2 on 2022-11-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0002_conversation_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latest',
            field=models.DateTimeField(blank=True),
        ),
    ]
