# Generated by Django 4.1.2 on 2022-11-06 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0004_alter_conversation_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latest',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
