# Generated by Django 4.1.2 on 2022-11-06 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0005_alter_conversation_latest_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='latest',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
