# Generated by Django 4.1.2 on 2022-11-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct_messages', '0006_alter_conversation_latest_alter_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='unread',
        ),
        migrations.AddField(
            model_name='conversation',
            name='a_unread',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='b_unread',
            field=models.BooleanField(default=False),
        ),
    ]
